name = "Solarplaza"
maintainer = "SmartSheep Studio"

frontend = "https://lian.solsynth.dev"

bind = "0.0.0.0:8445"
domain = "im.solsynth.dev"
secret = "LtTjzAGFLshwXhN4ZD4nG5KlMv1MWcsvfv03TSZYnT1VhiAnLIZFTnHUwR0XhGgi"

[debug]
database = false
print_routes = false

[paperclip]
endpoint = "http://localhost:8443"
grpc_endpoint = "localhost:7443"

[passport]
client_id = "solarplaza"
client_secret = "Z9k9AFTj^p"
endpoint = "http://localhost:8444"
grpc_endpoint = "localhost:7444"

[mailer]
name = "Alphabot <alphabot@smartsheep.studio>"
smtp_host = "smtp.exmail.qq.com"
smtp_port = 465
username = "alphabot@smartsheep.studio"
password = "gz937Zxxzfcd9SeH"

[security]
cookie_domain = "localhost"
cookie_samesite = "Lax"
access_token_duration = 300
refresh_token_duration = 2592000

[database]
dsn = "host=localhost user=postgres password=password dbname=hy_interactive port=5432 sslmode=disable"
prefix = "interactive_"
